language: ruby
rvm:
  - 2.0.0

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec

branches:
  only:
    - master

before_script:
  - psql -c 'create database pomodori_test;' -U postgres
