development:
  adapter: postgresql
  encoding: unicode
  database: pomodori_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pomodori_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: pomodori_production
  pool: 5
  username: pomodori
  password:
